language: ruby
services:
  - docker
env:
  global:
    - IMAGE_NAME=marcyin/geog0111
    - REGISTRY_USER=marcyin

before_script:
  - version="0.0.1"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker run -d -p 8888:8888 f0xy/geog0111 /bin/sh -c "ls -lah"
after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$DOCKER_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master

