language: ruby

services:
  - docker

env:
  global:
    - IMAGE_NAME=f0xy/geog0111
    - REGISTRY_USER=f0xy

before_script:
  - version="0.0.1"
script:
  - docker build -t geog0111 .
  - docker run -d -p 127.0.0.1:80:4567 geog0111 /bin/sh -c "ls -lah"
after_script:
  - docker images
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
