language: ruby
sudo: required
services:
  - docker
before_script:
  - DOCKER_USER=f0xy
script:
  - docker build -t geog0111 .
after_script:
  - docker images
deploy:
  provider: script
    skip_cleanup: true
    script: 
      - docker login -u $DOCKER_USER -p $REGISTRY_PASS
      - docker tag geog0111 $DOCKER_USER/:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USER/geog0111:$TRAVIS_BUILD_NUMBER
      - docker tag geog0111 $DOCKER_USER/geog0111:latest
      - docker push $DOCKER_USER/geog0111:latest
