language: ruby
services:
  - docker
before_script:
  - DOCKER_USER=f0xy
script:
  - docker build -t geog0111 .
after_script:
  - docker images
deploy:
  provider: script
  script: 
      - docker login -u $DOCKER_USER -p $REGISTRY_PASS
      - docker tag geog0111 $DOCKER_USER/:0.0.1
      - docker push $DOCKER_USER/geog0111:0.0.1
      - docker tag geog0111 $DOCKER_USER/geog0111:latest
      - docker push $DOCKER_USER/geog0111:latest
