name: uclgeog
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - matplotlib
  - ipyleaflet
  - ipython
  - ipywidgets
  - jupyter_console
  - nbconvert
  - jupyterlab
  - nbformat
  - git
  - ipykernel
  - pip
  - jupyter_contrib_nbextensions
  - jupyterthemes
  - nodejs
